# Generated by Django 6.0.5 on 2026-05-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_seed_demo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('prescription_code', models.CharField(max_length=32, unique=True)),
                ('medicine_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Issue', 'Issue')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('assigned_to', models.CharField(max_length=120)),
                ('created_at_label', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
