# Generated by Django 6.0.5 on 2026-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_seed_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('invoice_code', models.CharField(max_length=32, unique=True)),
                ('medicine_name', models.CharField(max_length=120)),
                ('units', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile', 'Mobile'), ('Insurance', 'Insurance')], max_length=20)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Refunded', 'Refunded')], default='Completed', max_length=20)),
                ('cashier_name', models.CharField(max_length=120)),
                ('sold_at_label', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
