# Generated by Django 6.0.5 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0006_seed_sales"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
