# Generated by Django 6.0.5 on 2026-05-13 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0007_medicineitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("stock_balance", models.PositiveIntegerField(default=0)),
                ("expiry_date", models.DateField()),
                (
                    "medicine_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_record",
                        to="pharmacy.medicineitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
